INFO 2025-09-03 20:51:39,165 autoreload 27960 1224 Watching for file changes with StatReloader
INFO 2025-09-03 20:53:44,417 autoreload 27960 1224 D:\BACKUP\Complete Projects\university_voting_system\university_voting_system\urls.py changed, reloading.
INFO 2025-09-03 20:53:45,639 autoreload 20036 24660 Watching for file changes with StatReloader
INFO 2025-09-03 21:19:52,583 autoreload 18164 20420 Watching for file changes with StatReloader
ERROR 2025-09-03 21:19:57,416 log 18164 5060 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: voting/login.html
ERROR 2025-09-03 21:19:57,425 basehttp 18164 5060 "GET / HTTP/1.1" 500 86986
INFO 2025-09-03 21:20:02,780 basehttp 18164 5060 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-09-03 21:20:03,932 basehttp 18164 5060 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4187
INFO 2025-09-03 21:20:19,975 basehttp 18164 5060 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4376
INFO 2025-09-03 21:20:40,772 basehttp 18164 5060 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-09-03 21:20:40,873 basehttp 18164 5060 "GET /admin/ HTTP/1.1" 200 15094
INFO 2025-09-03 21:20:54,069 basehttp 18164 5060 "GET /admin/voting/student/ HTTP/1.1" 200 17975
INFO 2025-09-03 21:20:54,463 basehttp 18164 5060 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-09-03 21:20:57,704 basehttp 18164 5060 "GET /admin/voting/student/1/change/ HTTP/1.1" 200 25630
INFO 2025-09-03 21:20:57,748 basehttp 18164 5060 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-09-03 21:21:11,494 basehttp 18164 5060 "GET /admin/voting/programme/add/?_to_field=id&_popup=1 HTTP/1.1" 200 6729
INFO 2025-09-03 21:21:11,535 basehttp 18164 5060 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-09-03 21:21:32,985 basehttp 18164 5060 "GET /admin/voting/department/add/?_to_field=id&_popup=1 HTTP/1.1" 200 6689
INFO 2025-09-03 21:21:33,027 basehttp 18164 5060 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-09-03 21:21:51,113 basehttp 18164 5060 "GET /admin/voting/faculty/add/?_to_field=id&_popup=1 HTTP/1.1" 200 5003
INFO 2025-09-03 21:21:51,249 basehttp 18164 5060 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-09-03 21:22:18,968 basehttp 18164 5060 "POST /admin/voting/faculty/add/?_to_field=id&_popup=1 HTTP/1.1" 200 366
INFO 2025-09-03 21:22:19,174 basehttp 18164 5060 "GET /static/admin/js/popup_response.js HTTP/1.1" 200 532
INFO 2025-09-03 21:22:22,101 basehttp 18164 5060 "POST /admin/voting/department/add/?_to_field=id&_popup=1 HTTP/1.1" 200 385
INFO 2025-09-03 21:22:24,707 basehttp 18164 5060 "POST /admin/voting/programme/add/?_to_field=id&_popup=1 HTTP/1.1" 200 355
INFO 2025-09-03 21:22:33,625 basehttp 18164 5060 "POST /admin/voting/student/1/change/ HTTP/1.1" 302 0
INFO 2025-09-03 21:22:33,671 basehttp 18164 5060 "GET /admin/voting/student/ HTTP/1.1" 200 18240
INFO 2025-09-03 21:22:33,708 basehttp 18164 5060 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-09-03 21:22:36,458 basehttp 18164 5060 "GET /admin/voting/student/1/change/ HTTP/1.1" 200 25715
INFO 2025-09-03 21:22:36,500 basehttp 18164 5060 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-09-03 21:23:03,789 basehttp 18164 5060 "POST /admin/voting/student/1/change/ HTTP/1.1" 302 0
INFO 2025-09-03 21:23:03,842 basehttp 18164 5060 "GET /admin/voting/student/ HTTP/1.1" 200 18240
INFO 2025-09-03 21:23:03,878 basehttp 18164 5060 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-09-03 21:40:33,259 basehttp 18164 12836 "GET /admin/voting/student/ HTTP/1.1" 302 0
INFO 2025-09-03 21:40:33,271 basehttp 18164 12836 "GET /admin/login/?next=/admin/voting/student/ HTTP/1.1" 200 4217
INFO 2025-09-03 21:40:50,656 basehttp 18164 12836 "POST /admin/login/?next=/admin/voting/student/ HTTP/1.1" 302 0
INFO 2025-09-03 21:40:51,024 basehttp 18164 12836 "GET /admin/voting/student/ HTTP/1.1" 200 75920
INFO 2025-09-03 21:40:51,060 basehttp 18164 12836 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-09-03 21:40:55,876 basehttp 18164 12836 "GET /admin/voting/student/209/change/ HTTP/1.1" 200 31941
INFO 2025-09-03 21:40:55,920 basehttp 18164 12836 "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2025-09-03 22:18:21,033 autoreload 18164 20420 D:\BACKUP\Complete Projects\university_voting_system\voting\views.py changed, reloading.
INFO 2025-09-03 22:18:23,607 autoreload 7700 6672 Watching for file changes with StatReloader
INFO 2025-09-03 22:23:44,271 autoreload 19856 18336 Watching for file changes with StatReloader
ERROR 2025-09-03 22:23:48,000 log 7700 17412 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
ERROR 2025-09-03 22:23:48,083 basehttp 7700 17412 "GET / HTTP/1.1" 500 86874
INFO 2025-09-03 22:24:09,428 autoreload 7700 6672 D:\BACKUP\Complete Projects\university_voting_system\university_voting_system\settings.py changed, reloading.
INFO 2025-09-03 22:24:09,694 autoreload 19856 18336 D:\BACKUP\Complete Projects\university_voting_system\university_voting_system\settings.py changed, reloading.
INFO 2025-09-03 22:24:12,980 autoreload 5672 20020 Watching for file changes with StatReloader
INFO 2025-09-03 22:24:12,993 autoreload 6112 24452 Watching for file changes with StatReloader
ERROR 2025-09-03 22:24:21,337 log 6112 7896 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: voting/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: voting/base.html
ERROR 2025-09-03 22:24:21,357 basehttp 6112 7896 "GET / HTTP/1.1" 500 131603
ERROR 2025-09-03 22:24:43,394 log 6112 7896 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: voting/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: voting/base.html
ERROR 2025-09-03 22:24:43,400 basehttp 6112 7896 "GET / HTTP/1.1" 500 131603
ERROR 2025-09-03 22:24:45,242 log 6112 7896 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: voting/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: voting/base.html
ERROR 2025-09-03 22:24:45,249 basehttp 6112 7896 "GET / HTTP/1.1" 500 131603
ERROR 2025-09-03 22:25:03,843 log 6112 7896 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\urls\base.py", line 81, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'voting'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\user\AppData\Roaming\Python\Python313\site-packages\django\urls\base.py", line 92, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'voting' is not a registered namespace
ERROR 2025-09-03 22:25:03,851 basehttp 6112 7896 "GET / HTTP/1.1" 500 141933
